---
title: "CMS_biomarker"
output: html_document
date: '2023-07-20'
---
```{r}
library(DeepCC)
library(gaofenglib)
library(survival)
library(parallel)
library(gfplot)
library(glmnet)
library(ggplot2)
library(gghalves)
library(IOBR)
library(plyr)
library(DESeq2)
library(tidyverse)
library(gt)
library(tableone)
library(tidyverse)
library(HTSanalyzeR2)
library(RColorBrewer)
library(forestplot)
library(reshape2)
library(survcomp)
library(GSVA)
library(ComplexHeatmap)
library(pheatmap)
library(scales)
library(RColorBrewer)
library(Hmisc)
library(NMF)
library(ggcorrplot)
library(ggpubr)
library(ggsci)
library(tidyr)
library(survivalROC)
library(extrafont)
loadfonts()
Arial <- Type1Font(family = "Arial",
                   metrics = c("ArialMT.afm",
                               "ArialMT-Bold.afm", 
                               "ArialMT-Italic.afm",
                               "ArialMT-BoldItalic.afm")
                   )
pdfFonts(Arial = Arial)
```

```{r setup, include=FALSE}

load("/Users/gaibaowen/Downloads/CMS biomarker/CMS_biomarker_new/data/sig_genes.rdata")
load("/Users/gaibaowen/Downloads/CMS biomarker/CMS_biomarker_new/data/crc_combat.rdata")
```

```{r}
datasets <- crc_combat
clin_all <- crc_clin_all
rownames(clin_all) <- clin_all$id
get_survival <- function (clin)
{
    survival::Surv(clin[, "dfs.delay"], clin[, "dfs.event"] == 1)
}
i = 1
dat <- datasets[[i]][, sig.genes]
clin <- clin_all[substr(rownames(dat), 1, 12), ]
sur <- get_survival(clin)
ind <- !is.na(sur)
dat <- data.frame(scale(dat[ind, ]))
sur <- sur[ind, ]
model <- coxph(sur ~ .,data=dat)

#r <- summary(model)
#r$concordance
#low <- r$concordance[1]-1.96*r$concordance[2]
#high <- r$concordance[1]+1.96*r$concordance[2]
```



```{r}
pdf(file="/Users/gaibaowen/Downloads/CMS biomarker/CMS_biomarker_new/result/survival_analysis.pdf",width = 10,height = 8)
p_list <- NULL
for(i in 1:length(datasets)) {
  title <- names(datasets)[i]
    # dat <- scale(datasets[[i]][, signature])
    dat <- data.frame(scale(datasets[[i]][, sig.genes]))
    clin <- clin_all[substr(rownames(dat), 1, 12), ]
    sur <- get_survival(clin)
    ind <- !is.na(sur) #& clin$stage %in% stage.oi
    dat <- dat[ind, ]
    sur <- sur[ind, ]
  
  rs <- predict(model, dat)
    # rs <- predict(fit, dat, s = s)
  #if(i == 1) rs_cut <- median(rs)
  # rs_cut <- median(rs)
  if(i == 1) rs_cut <- calc_cutoff_survivalroc(sur, rs, 60)
  labs <- factor(rs > rs_cut, levels = c(F, T), labels = c("Low Risk", "High Risk"))
  
  p <- plot_KMCurve(sur, labs, ylab="DFS", color = c("#377EB8", "#E41A1C"), legend.pos = "none", title = title, xlab="Months", limit = 60)
  p_list[i] <-list(p) 
}
p_res <- plot_grid(plotlist = p_list,ncol = 2)
print(p_res)
dev.off()
```


```{r}
#Oncotype_DX生存分析

pdf(file="/Users/gaibaowen/Downloads/CMS biomarker/CMS_biomarker_new/result/survival_analysis_oncotypeDX.pdf",width = 10,height = 8)
p_list <- NULL
for(i in 1:length(datasets)) {
  title <- names(datasets)[i]
    # dat <- scale(datasets[[i]][, signature])
    dat <- data.frame(scale(datasets[[i]]))
    clin <- clin_all[substr(rownames(dat), 1, 12), ]
    sur <- get_survival(clin)
    ind <- !is.na(sur) #& clin$stage %in% stage.oi
    dat <- dat[ind, ]
    sur <- sur[ind, ]
  
    oncotype <- calc_oncotypedx_crc(dat)
    rs_oncotype <- oncotype$oncotypeDX_score
    labs <- factor(oncotype$oncotypeDX_class,levels = c("Low","Intermediate","High"),labels = c("Low Risk","Intermediate","High Risk"))

  
  p <- plot_KMCurve(sur, labs, ylab="DFS", color = c("#377EB8","#42B540", "#E41A1C"), legend.pos = "top", title = title, xlab="Months", limit = 60)
  p_list[i] <-list(p) 
}
p_res <- plot_grid(plotlist = p_list,ncol = 2)
print(p_res)
dev.off()
```


```{r}
#CMS生存分析

get_survival <- function (clin)
{
    survival::Surv(clin[, "dfs.delay"], clin[, "dfs.event"] == 1)
}
i=1
dat <- datasets[[i]]
clin <- clin_all[substr(rownames(dat), 1, 12), ]
sur <- get_survival(clin)
ind <- !is.na(sur)
dat <- data.frame(scale(dat[ind, ]))
sur <- sur[ind, ]
clin <- clin[ind,]

ind <- !is.na(clin$cms)
dat <- dat[ind,]
clin <- clin[ind,]
sur <- sur[ind,]

model <- coxph(sur ~clin$cms,data=dat)
clin_all$cms[which(clin_all$cms=="NOLBL")] <- NA

pdf(file="/Users/gaibaowen/Downloads/CMS biomarker/CMS_biomarker_new/result/survival_analysis_CMS.pdf",width = 10,height = 8)
p_list <- NULL
for(i in 1:length(datasets)) {
  title <- names(datasets)[i]

    dat <- data.frame(scale(datasets[[i]]))
    clin <- clin_all[substr(rownames(dat), 1, 12), ]
    sur <- get_survival(clin)
    ind <- !is.na(sur) #& clin$stage %in% stage.oi
    dat <- dat[ind, ]
    sur <- sur[ind, ]
    clin <- clin[ind,]
  
    ind <- !is.na(clin$cms)
    dat <- dat[ind,]
    clin <- clin[ind,]
    sur <- sur[ind,]
     
    rs <- predict(model, dat)
    # rs <- predict(fit, dat, s = s)
  #if(i == 1) rs_cut <- median(rs)
  # rs_cut <- median(rs)
  if(i == 1) rs_cut <- calc_cutoff_survivalroc(sur, rs, 60)
  labs <- factor(rs > rs_cut, levels = c(F, T), labels = c("Low Risk", "High Risk"))
  
  p <- plot_KMCurve(sur, labs, ylab="DFS", color = c("#377EB8", "#E41A1C"), legend.pos = "top", title = title, xlab="Months", limit = 60)
  p_list[i] <-list(p) 
}
p_res <- plot_grid(plotlist = p_list,ncol = 2)
print(p_res)
dev.off()
```





```{r}
#factor_analysis
datasets_list <- names(datasets)
tmp <- lapply(1:length(datasets_list), function(i) {
  pt_id <- substr(rownames(lab.df)[lab.df$Cohort %in% datasets_list[[i]]], 1, 12)
  clin <- clin_all[pt_id, ]
  rs <- lab.df[rownames(clin), ]$RiskGroup
  sur <-  get_survival(clin)
  
  clin$sex <- factor(clin$sex, levels = c("F", "M"))
  clin$location <- factor(clin$location,levels = c("L","R"))
  clin$mmr <- factor(clin$mmr,levels = c("msi","mss"))
 
  
  
  factor_name <- c("sex", "age", "location", "tnm.stage",
                   "mmr", "cms")

  clin_factors <- data.frame(rs=rs, clin[, factor_name])
  
  rfs <- sur
  gaofenglib::factor_analysis_cox(clin_factors, rfs, limit = 60, string = T, ignore.mul.auto = F)
})

factor_analysis <- do.call(cbind, tmp)
factor_analysis
write.csv(factor_analysis,file = "/Users/gaibaowen/Downloads/CMS biomarker/CMS_biomarker_new/result/factor_analysis.csv")
```





```{r}
lab.df <- lapply(1:length(datasets), function(i) {
  title <- names(datasets)[i]
    # dat <- scale(datasets[[i]][, sig.genes])
    dat <- data.frame(scale(datasets[[i]][, sig.genes]))
    clin <- clin_all[substr(rownames(dat), 1, 12), ]
    sur <- get_survival(clin)
    ind <- !is.na(sur) #& clin$stage %in% stage.oi
    dat <- dat[ind, ]
    sur <- sur[ind, ]
    
    
  rs <- predict(model, dat)
  # rs <- predict(fit, dat, s = s)
  if(i == 1) rs_cut <- calc_cutoff_survivalroc(sur, rs, 60)
  labs <- factor(rs > rs_cut, levels = c(F, T), labels = c("Low Risk", "High Risk"))


  data.frame(Cohort=title,
             RiskGroup=labs,
             RiskScore=rs
             )

})

lab.df <- do.call(rbind, lab.df)
save(lab.df, rs_cut, file = "/Users/gaibaowen/Downloads/CMS biomarker/CMS_biomarker_new/result/labs.RData")
```



```{r}
#roc/risk score
p_list <- NULL
for(i in 1:length(datasets)) {
  title <- names(datasets)[i]
    # dat <- scale(datasets[[i]][, signature])
    dat <- data.frame(scale(datasets[[i]][, sig.genes]))
    clin <- clin_all[substr(rownames(dat), 1, 12), ]
    sur <- get_survival(clin)
    ind <- !is.na(sur) #& clin$stage %in% stage.oi
    dat <- dat[ind, ]
    sur <- sur[ind, ]
  
  rs <- predict(model, dat)
    # rs <- predict(fit, dat, s = s)
  #if(i == 1) rs_cut <- median(rs)
  # rs_cut <- median(rs)
  if(i == 1) rs_cut <- calc_cutoff_survivalroc(sur, rs, 60)
  
  event <- clin[ind,]

# p1 <- plot_RiskScore(rs - rs_cut, factor(event$dfs.event, labels = c("Alive", "Death")), color = c("#0073C2FF", "#EFC000FF")) + labs(title = title, y = "Adjusted risk score") 
  
p1 <- plot_RiskScore(rs - rs_cut, factor(event$dfs.event, labels = c("Disease-Free", "Recurrence")), palette = "jco") + labs(title = title, y = "Adjusted risk score") 

p2 <- plot_TimeROC(rs, sur, 
                 time_points =  c(24, 36, 60), groups = c("2-Year", "3-Year", "5-Year"),palette = "jco",
                 title= title)
  p_list[i] <-list(p2) 
}
p_res <- plot_grid(plotlist = p_list,ncol = 2)

pdf(file="/Users/gaibaowen/Downloads/CMS biomarker/CMS_biomarker_new/result/roc2.pdf",width = 10,height = 8)
p_res
dev.off()
```



```{r}
# clean data
load("/Users/gaibaowen/Downloads/CMS biomarker/CMS biomarker/data/crc_tcga_count.RData")

pt_id <- intersect(rownames(lab.df), rownames(crc_tumor))
lab.df <- lab.df[pt_id,]
data <- crc_tumor[pt_id,]
group <- lab.df[rownames(data), ]$RiskGroup
rs <- lab.df[rownames(data), ]$RiskScore
```

# DEseq2 based on count data
```{r}
data <- round(t(data))
colData <- data.frame(row.names=colnames(data), group)

dds <- DESeqDataSetFromMatrix(data, colData, design= ~ group)
dds <- DESeq(dds)  
res <- results(dds)
# summary(res)
resdata <-  as.data.frame(res)
resdata <- resdata[!is.na(resdata$padj),]
save(resdata, file = "/Users/gaibaowen/Downloads/CMS biomarker/CMS_biomarker_new/result/de_genes.RData")
output <- resdata
table(output$padj < 0.05 & abs(output$log2FoldChange) > 1)
de.genes <- rownames(output)[output$padj < 0.05 & abs(output$log2FoldChange) > 2]
```

# GO analysis for degenes
```{r fig.width=6}
genes <- as.character(unique(de.genes))
# include GO (GO:BP, GO:MF, GO:CC to select a particular GO branch), KEGG, REAC, TF, MIRNA, CORUM, HP, HPA, WP.
gostres <- gprofiler2::gost(genes, sources = "GO")
gsea <- gostres$result %>% arrange(p_value)
p <- plot_GO(gsea, n = 10) + scale_y_discrete(labels = function(x) str_wrap(x, width=40)) +
  scale_color_gradient2(low = "#3b8d99",mid = "#6b6b83", high = "#aa4b6b",midpoint = median(-log10(gsea$p_value))) 
  # scale_color_gradient(low = "#659999", high = "#f4791f")

p
ggsave(p, file = "../figures/degene_GO.pdf", width = 7, height = 4)
```

```{r}
library(clusterProfiler)
msigdb <- msigdbr::msigdbr()
c25 <- msigdb %>% filter(gs_cat %in% c("C2","C5"))
c25$gs_name <- gsub("_", " ",c25$gs_name)
# c25$gs_name <- Hmisc::capitalize(tolower(c25$gs_name))

genes <- as.character(unique(de.genes))
self_info <-c25 %>% dplyr::select(gs_name, entrez_gene)
gene_list <- bitr(genes, fromType = "SYMBOL", toType = "ENTREZID",OrgDb = "org.Hs.eg.db")$ENTREZID

self_enrich <- enricher(gene_list, TERM2GENE = self_info,pvalueCutoff = 0.05,qvalueCutoff = 0.05)
result <- self_enrich@result
# write.csv(result, file = "../tables/riskgroup_degene_go.csv", quote = F, row.names = F)
# 
p <-dotplot(self_enrich) +theme(axis.text.y = element_text(size = 10)) +
  scale_color_gradient2(low = "#C06C84",mid = "#6C5B7B", high = "#355C7D", midpoint = median(result[1:10,]$p.adjust))
  # scale_color_viridis(discrete = F, guide=FALSE) 
p
ggsave(p, file = "../figures/degene_C2C5.pdf", width = 7, height = 4)
```


# heatmap for degenes
```{r fig.width=12}

data <- datasets[[1]]
data <- data[rownames(data) %in% rownames(labs),]
labs <- lab.df[lab.df$Cohort=="TCGA",]
rs <- labs$RiskScore
group <- labs$RiskGroup
o <- order(rs)

df.plot <- t(scale(data[o, de.genes]))

cutoff <- 1
df.plot[df.plot > cutoff] <- cutoff
df.plot[df.plot < -cutoff] <- -cutoff

annot <- data.frame(RiskGroup=group[o])
rownames(annot) <- colnames(df.plot)

risk_color <- c("#377EB8", "#E41A1C")
names(risk_color) <- levels(group)

annotation_colors <- list(RiskGroup=risk_color)

p <- pheatmap::pheatmap(df.plot, cellwidth = 1, cellheight = 10, show_rownames = T,#treeheight_row = 0,
                   cluster_cols = F, fontsize_row = 5, annotation_col = annot, annotation_colors = annotation_colors,
                   show_colnames = F, main = "TCGA")
p
ggsave("/Users/gaibaowen/Downloads/CMS biomarker/CMS_biomarker_new/result/degene_heatmap_28.pdf", p, width = 15, height = 8)
```


# GSEA
```{r}
data4enrich <- output$log2FoldChange
names(data4enrich) <- rownames(output)
hits <- de.genes

nwaPvalues <- output$padj
names(nwaPvalues) <- rownames(output)

library(HTSanalyzeR2)
# listOfGeneSetCollections <- list(MSigDB=MSigDBGeneSets("h"))
# res <- HTSanalyzeR2Pipe(data4enrich, hits, listOfGeneSetCollections=listOfGeneSetCollections, initialIDs = "SYMBOL", cores = 40, msigdbGSCs = "MSigDB")

doParallel::registerDoParallel(8)
listOfGeneSetCollections <- list(MSigDB=do.call(c, lapply(c("H","C1","C3" ,"C2","C4", "C5","C6","C7"), function(x) MSigDBGeneSets("Hs", x))))
res <- HTSanalyzeR2Pipe(data4enrich, hits, listOfGeneSetCollections=listOfGeneSetCollections, initialIDs = "SYMBOL", cores = 8, msigdbGSCs = "MSigDB", doNWA = F, nwaPvalues = nwaPvalues, nwAnalysisFdr = 1e-5)

#reportAll(res$gsca, res$nwa, reportDir = "HTSanalyzerReport")

gsea.df <- res$gsca@result$GSEA.results$MSigDB

gsea.df <- gsea.df[gsea.df$Adjusted.Pvalue < 0.05, ]
save(gsea.df, file = "../rslt/gsea_result.RData")
# write.csv(gsea.df, file = "../tables/riskgroup_gsea_all.csv", quote = F, row.names = F)
```

```{r}
sig.pathway <- gsea.df[intersect(grep("HALLMARK", gsea.df$Gene.Set.Term), which(gsea.df$Adjusted.Pvalue < 0.05)), ]$Gene.Set.Term

l <- lapply(seq(sig.pathway), function(i) {
  gfplot::ggGSEA(res$gsca@geneList, listOfGeneSetCollections$MSigDB[[sig.pathway[i]]],
                   title = gsub("HALLMARK_", "", sig.pathway[i]))
})

p <- plot_grid(plotlist = l, ncol = 2)
ggsave("../figures/gsea_hallmark.pdf", width = 8, height = length(l)/2 * 2.5)
```

# GSEA hallmark barplot
```{r fig.width=8}
load("../rslt/gsea_result.RData")
gsea_hallmark <-  gsea.df[intersect(grep("HALLMARK", gsea.df$Gene.Set.Term), which(gsea.df$Adjusted.Pvalue < 0.05)), ]
gsea_hallmark$Gene.Set.Term <- str_match(gsea_hallmark$Gene.Set.Term, pattern = "(?<=_).+")
gsea_hallmark$Gene.Set.Term <- gsub(gsea_hallmark$Gene.Set.Term, pattern = "_", replacement = " ")
df_plot <- arrange(gsea_hallmark, Observed.score)
df_plot$Gene.Set.Term <- factor(df_plot$Gene.Set.Term, levels = df_plot$Gene.Set.Term)
df_plot$clr <- ifelse(df_plot$Observed.score < 0, "down", "up")
p <- 
  ggplot(df_plot, aes(x = Gene.Set.Term, y = Observed.score, fill = clr)) + 
  geom_bar(stat="identity") + coord_flip() + 
  # scale_fill_manual(values = c( "#00A1D5FF", "#B24745FF"))+
  scale_fill_manual(values = c( "#375E97", "#FE6542"))+
  labs(y = "Enrichment score", x = "Hallmark of cancer") + 
  theme(legend.position="none")
p
ggsave(p, filename = "/Users/gaibaowen/Downloads/CMS biomarker/CMS_biomarker_new/result/GSEA_hallmark_barplot.pdf", width = 10, height = 6)
```

# GSEA GO term barplot
```{r fig.width=8}
load("../rslt/gsea_result.RData")
gsea_pathway <- gsea.df[grepl(gsea.df$Gene.Set.Term, pattern = "^GO"),]
gsea_pathway$Gene.Set.Term <- str_match(gsea_pathway$Gene.Set.Term, pattern = "(?<=_).+")
gsea_pathway$Gene.Set.Term <- gsub(gsea_pathway$Gene.Set.Term, pattern = "_", replacement = " ")
df_plot <- gsea_pathway[1:15,]
df_plot <- arrange(df_plot, Observed.score)
df_plot$Gene.Set.Term <- factor(df_plot$Gene.Set.Term, levels = df_plot$Gene.Set.Term)
df_plot$clr <- ifelse(df_plot$Observed.score < 0, "down", "up")
p <- 
ggplot(df_plot, aes(x = Gene.Set.Term, y = Observed.score, fill = clr)) + 
  geom_bar(stat="identity") + coord_flip() + 
  # scale_fill_manual(values = c( "#00A1D5FF", "#B24745FF"))+
  scale_fill_manual(values = c( "#375E97", "#FE6542"))+
  scale_x_discrete(labels = function(x) str_wrap(x, width=50)) +
  labs(y = "Enrichment score", x = "GO Terms") + 
  theme(legend.position="none")
p
ggsave(p, filename = "../figures/GSEA_GO_barplot.pdf", width = 10, height = 6)
```


# Estimate
```{r}
data <- t(gene_exp)
estimate <- deconvo_tme(eset = data, method = "estimate")
```

```{r}
group <- lab.df[lab.df$Cohort=="TCGA",]
name <- rownames(group)
group <- as.data.frame(group[,2])
rownames(group) <- name
colnames(group)[1] <- "group"
group$ID <- rownames(group)

df_data <- as.data.frame(estimate)
df_data$ID <- substr(df_data$ID,1,12)

df_data <- merge(df_data,group,by="ID")

df_plot <- melt(df_data)
df_plot$variable <- str_match(df_plot$variable, pattern = ".+(?=_)")

ggboxplot(df_plot, x = "variable", y = "value", ylab = "Estimate Scores", fill = "group") + 
  stat_compare_means(aes(group = group), label = "p.signif",label.y = max(df_plot$value)*1.05)+
  scale_fill_manual(values = c("#C0C0C0", "#0F7BA7"))+
  scale_x_discrete(labels = function(x) str_wrap(gsub(x, pattern = "_", replacement = " "), width=40))+ theme_light() + 
  theme(axis.text.x = element_text(angle=45, hjust = 1, size = 12,
                                   color = "black"),
        axis.text.y = element_text(color = "black", size = 12),
        axis.title.y = element_text(color = "black", size = 12),
        axis.title.x = element_blank(), 
        axis.line = element_line(color = "black", size = 0.5),
        plot.title = element_text(color = "black", size = 20, hjust = 0.5),
        legend.title = element_blank(),
        legend.position = "top",
        legend.text = element_text(color = "black",size = 12)
        )
```


# immune cell infiltration
# ssGSEA
```{r}
data <- t(gene_exp)
gene_list <- readxl::read_excel("/Users/gaibaowen/Downloads/CMS biomarker/CMS biomarker/mmc3.xlsx")[,1:2]
list <- split(as.matrix(gene_list)[,1], gene_list[,2])
gsva_matrix <- gsva(data, 
                    list, 
                    method='ssgsea', 
                    kcdf='Gaussian', 
                    abs.ranking=TRUE)
ssgsea <- as.data.frame(t(gsva_matrix))
```

```{r fig.height=6, fig.width=8}
ssgsea$ID <- substr(rownames(ssgsea),1,12)
df <- merge(ssgsea,group,by="ID")
colnames(df) <- gsub(colnames(df), pattern = ".", replacement = " ", fixed = T)
df <- df[,c(1:5,9,10,15,17,20:22,24,28,29,30)]
df_plot <- melt(df)

# tmp <- apply(ssgsea, 2, mean)
# ind <- order(tmp, decreasing = T)
# df_plot$variable <- factor(df_plot$variable, levels = unique(df_plot$variable)[ind])

p <- 
ggboxplot(df_plot, x = "variable", y = "value", ylab = "Immune Infiltration Scores", fill = "group") + 
  stat_compare_means(aes(group = group), label = "p.signif",label.y = max(df_plot$value)*1.05)+
  scale_fill_manual(values = c("#C0C0C0", "#0F7BA7"))+
  scale_x_discrete(labels = function(x) str_wrap(gsub(x, pattern = "_", replacement = " "), width=40))+ theme_light() + 
  theme(axis.text.x = element_text(angle=45, hjust = 1, size = 12,
                                   color = "black"),
        axis.text.y = element_text(color = "black", size = 12),
        axis.title.y = element_text(color = "black", size = 12),
        axis.title.x = element_blank(), 
        axis.line = element_line(color = "black", size = 0.5),
        plot.title = element_text(color = "black", size = 20, hjust = 0.5),
        legend.title = element_blank(),
        legend.position = "top",
        legend.text = element_text(color = "black",size = 12)
        )
p

pdf(file = "/Users/gaibaowen/Downloads/CMS biomarker/CMS_biomarker_new/result/immuneTcell.pdf")
print(p)
dev.off()

```

# other immune cell algorithm
```{r}
cibersort <- deconvo_tme(eset = data, method = "cibersort", arrays = FALSE, perm = 200)
epic <- deconvo_tme(eset = data, method = "epic", arrays = FALSE)
mcp <- deconvo_tme(eset = data, method = "mcpcounter")
xcell <- deconvo_tme(eset = data, method = "xcell",arrays = FALSE)
quantiseq <- deconvo_tme(eset = data, tumor = TRUE, arrays = FALSE, scale_mrna = TRUE, method = "quantiseq")

immune_cell <- list(cibersort = cibersort[,-c(24:26)],
                    epic = epic[,-9],
                    mcp = mcp,
                    xcell = xcell[,-c(66:68)],
                    quantiseq = quantiseq[,-12])
immune_cell <- lapply(immune_cell, function(x) {
  x <- data.frame(x[,-1])
  rownames(x) <- substr(colnames(data),1,12)
  colnames(x) <- str_match(colnames(x), pattern = ".+(?=_)")
  x
})
```

```{r fig.height=6, fig.width=8}
p_list <- NULL
for (i in 1:length(immune_cell)) {
  df <- immune_cell[[i]]
  df$ID <- rownames(df)
  df <- data.frame(merge(df,group,by="ID"))
  rownames(df) <- df$ID
  df <- df[,-1]
# colnames(df) <- gsub(colnames(df), pattern = ".", replacement = " ", fixed = T)
  df_plot <- melt(df)

p <- 
ggboxplot(df_plot, x = "variable", y = "value", ylab = "Immune Infiltration Scores", fill = "group") + 
  stat_compare_means(aes(group = group), label = "p.signif",label.y = max(df_plot$value)*1.05)+
  scale_fill_manual(values = c("#C0C0C0", "#0F7BA7"))+
  scale_x_discrete(labels = function(x) str_wrap(gsub(x, pattern = "_", replacement = " "), width=40))+ theme_light() + 
  theme(axis.text.x = element_text(angle=45, hjust = 1, size = 12,
                                   color = "black"),
        axis.text.y = element_text(color = "black", size = 12),
        axis.title.y = element_text(color = "black", size = 12),
        axis.title.x = element_blank(), 
        axis.line = element_line(color = "black", size = 0.5),
        plot.title = element_text(color = "black", size = 20, hjust = 0.5),
        legend.title = element_blank(),
        legend.position = "top",
        legend.text = element_text(color = "black",size = 12)
        )
p_list[i] <- list(p)
}


pdf(file = "/Users/gaibaowen/Downloads/CMS biomarker/CMS_biomarker_new/result/immunecell_all.pdf")
print(p_list)
dev.off()
```


```{r fig.height=6, fig.width=14}
p_list <- NULL
for (i in 1:length(immune_cell) ) {
  labs <- lab.df[lab.df$Cohort=="TCGA",]
  rs <- labs$RiskScore
  o <- order(rs)  
  data <- immune_cell[[i]]
  data <- data[rownames(data) %in% group$ID,]
  ind <- apply(data, 2, sum) != 0
  data <- data[,ind]
  df.plot <- t(scale(data[o, ]))
  
  cutoff <- 1
  df.plot[df.plot > cutoff] <- cutoff
  df.plot[df.plot < -cutoff] <- -cutoff
  
  annotation <- data.frame(RiskGroup=group[o,])
  annotation$RiskGroup.group<- factor(annotation$RiskGroup.group,levels = c("Low Risk","High Risk"),labels = c("Low_Risk","High_Risk"))
  annot <- data.frame(RiskGroup=annotation[,1])
  rownames(annot) <- annotation$RiskGroup.ID
  
 
  
  annotation_colors <- list(RiskGroup=c(Low_Risk="#377EB8",High_Risk="#E41A1C"))
  
  p <- pheatmap::pheatmap(df.plot, cellwidth = 1, cellheight = 10, show_rownames = T,
                     show_colnames = F,cluster_cols = F,cluster_rows = T, 
                     annotation_col = annot, annotation_colors = annotation_colors,
                     main = paste0("Immune Cell Infiltration Score, ", names(immune_cell)[i]))
p_list[i] <- list(p)
}
pdf(file = "/Users/gaibaowen/Downloads/CMS biomarker/CMS_biomarker_new/result/immunecell_heatmap.pdf",height =8,width = 16)
print(p_list[[5]])
dev.off()
```

```{r}
data <- t(gene_exp)
sig_res<-calculate_sig_score(pdata           = NULL,
                             eset            = data,
                             signature       = signature_collection,
                             method          = "pca",
                             adjust_eset = T,
                             mini_gene_count = 2)
```

```{r fig.height=6, fig.width=8}
for (i in 1:length(sig_group)) {
try({
print(i)
# i = 32
sig_list <- sig_group[[i]]
if(length(sig_list) > 20) {
  sig_list <- sig_list[1:20]
} else{
  sig_list <- sig_list
}
sig_res$group <- group
df <- melt(sig_res[,c(2, which(colnames(sig_res) %in% sig_list), 261)])

df$variable <- factor(df$variable, levels = sig_list)
# df$variable <- gsub(df$variable, pattern = "_", replacement = " ")

font_size <- ifelse(length(sig_list) > 15, 10,14)

p <-
ggboxplot(df, x = "variable", y = "value", ylab = "Signature score", fill = "group") + 
  stat_compare_means(aes(group = group), label = "p.signif",label.y = max(df$value)*1.05)+
  scale_fill_manual(values = c("#377EB8", "#E41A1C"))+
  scale_x_discrete(labels = function(x) str_wrap(gsub(x, pattern = "_", replacement = " "), width=24))+
  ggtitle(names(sig_group)[i]) + theme_light() + 
  theme(axis.text.x = element_text(angle=45, hjust = 1, size = font_size,
                                   color = "black"),
        axis.text.y = element_text(color = "black", size = font_size),
        axis.title.y = element_text(color = "black", size = font_size),
        axis.title.x = element_blank(), 
        axis.line = element_line(color = "black", size = 0.5),
        plot.title = element_text(color = "black", size = 20, hjust = 0.5),
        legend.title = element_blank(),
        legend.position = "bottom",
        legend.text = element_text(color = "black",size = 12)
        )
print(p)
}, silent = T)
  
# ggsave(p, filename = "../figures/IOBR/IS_signature.pdf", width = 8, height = 6)
}
```



```{r}
#immune
tcga <- crc_combat[[1]]
high_label <- lab.df[lab.df$Cohort=="TCGA" & lab.df$RiskGroup=="High Risk",]
low_label <- lab.df[lab.df$Cohort=="TCGA" & lab.df$RiskGroup=="Low Risk",]
lab_tcga <- lab.df[lab.df$Cohort=="TCGA",]
lab_tcga$ID <- rownames(lab_tcga)



#IOBR包的IPS

ips <- IOBR::deconvo_tme(eset = t(tcga), method = "ips", plot= FALSE)
ips <- merge(ips,lab_tcga,by="ID")
ips <- ips[,c(1,7,9)]
colnames(ips) <- c("ID","expression","group")
x=colnames(ips)[3]
y=colnames(ips)[2]

group=levels(factor(ips$group))
comp=combn(group,2)
my_comparisons=list()
for(i in 1:ncol(comp)){my_comparisons[[i]]<-comp[,i]}
variable <- c('Low Risk','High Risk')
my_sort <-factor(variable,levels = variable)

p1 <- ggplot(ips)+
  geom_half_violin(aes(as.numeric(factor(group,levels = my_sort))+0.1,expression,fill=factor(group,levels = my_sort)),side = 'r',cex=0.8)+
  geom_boxplot(aes(as.numeric(factor(group,levels = my_sort))+0.1,expression,fill=factor(group,levels = my_sort)),width=0.1,cex=0.8)+
  geom_jitter(aes(as.numeric(factor(group,levels = my_sort))-0.1,expression,color=factor(group,levels = my_sort)),width = 0.1,size=0.5)+
  scale_x_continuous(breaks = unique(as.numeric(factor(ips$group,levels = my_sort))), 
labels = unique(factor(ips$group,levels = my_sort)))+
  labs(title = "IPS",x=NULL)+
  theme(plot.title = element_text(hjust = 0.5))
#+stat_compare_means(comparisons = my_comparisons,method = "wilcox",label = "p.signif")+
p1 <- p1+scale_color_lancet()+scale_fill_lancet()


#miracle
library(Miracle)
miracle <- Calculate_Miracle(t(tcga),"gene")
miracle$ID <- rownames(miracle)
miracle <- merge(miracle,lab_tcga,by="ID")
miracle <- miracle[,c(1,5,7)]
colnames(miracle) <- c("ID","expression","group")

group=levels(factor(miracle$group))
comp=combn(group,2)
my_comparisons=list()
for(i in 1:ncol(comp)){my_comparisons[[i]]<-comp[,i]}

p2 <- ggplot(miracle)+
  geom_half_violin(aes(as.numeric(factor(group,levels = my_sort))+0.1,expression,fill=factor(group,levels = my_sort)),side = 'r',cex=0.8)+
  geom_boxplot(aes(as.numeric(factor(group,levels = my_sort))+0.1,expression,fill=factor(group,levels = my_sort)),width=0.1,cex=0.8)+
  geom_jitter(aes(as.numeric(factor(group,levels = my_sort))-0.1,expression,color=factor(group,levels = my_sort)),width = 0.1,size=0.5)+
  scale_x_continuous(breaks = unique(as.numeric(factor(miracle$group,levels = my_sort))), 
labels = unique(factor(miracle$group,levels = my_sort)))+
  labs(title = "MIRACLE",x=NULL)+
  theme(plot.title = element_text(hjust = 0.5))
#+stat_compare_means(comparisons = my_comparisons,method = "wilcox",label = "p.signif")+
p2 <- p2+scale_color_lancet()+scale_fill_lancet()

#TMB
library(maftools)
load("/Users/gaibaowen/Downloads/CMS biomarker/CMS biomarker/data/tcga_crc_updata_20220716_snv_maf.RData")
xlsx_all <- rbind(snv_coad_maf,snv_read_maf)
xlsx_clin <- data.frame(ID= lab_tcga$ID,Tumor_Sample_Barcode=lab_tcga$RiskGroup)
xlsx_clin$ID <- substr(xlsx_clin$ID,1,12)
maf_all <- maftools::read.maf(maf = xlsx_all, clinicalData = xlsx_clin , isTCGA =T)  #这里的xlsx_clin是一个dataframe，里面一列是12位的Tumor_Sample_Barcode，另外一列是你的分组（这里例如列名是Cluster）

getSampleSummary(maf_all)
plotmafSummary(maf = maf_all, rmOutlier = TRUE, addStat = 'median', dashboard = TRUE, titvRaw = FALSE)
tmb <- tmb(maf = maf_all)
colnames(tmb)[1] <- "ID"

lab_tcga2 <- lab_tcga
lab_tcga2$ID <- substr(lab_tcga2$ID,1,12)
tmb <- merge(tmb,lab_tcga2,by="ID")
tmb <- tmb[,c(1,4,6)]
colnames(tmb) <- c("ID","expression","group")
group=levels(factor(tmb$group))
comp=combn(group,2)
my_comparisons=list()
for(i in 1:ncol(comp)){my_comparisons[[i]]<-comp[,i]}

p3 <- ggplot(tmb)+
  geom_half_violin(aes(as.numeric(factor(group,levels = my_sort))+0.1,expression,fill=factor(group,levels = my_sort)),side = 'r',cex=0.8)+
  geom_boxplot(aes(as.numeric(factor(group,levels = my_sort))+0.1,expression,fill=factor(group,levels = my_sort)),width=0.1,cex=0.8)+
  geom_jitter(aes(as.numeric(factor(group,levels = my_sort))-0.1,expression,color=factor(group,levels = my_sort)),width = 0.1,size=0.5)+
  scale_x_continuous(breaks = unique(as.numeric(factor(tmb$group,levels = my_sort))), 
labels = unique(factor(tmb$group,levels = my_sort)))+
  labs(title = "TMB",x=NULL)+
  theme(plot.title = element_text(hjust = 0.5))
#+stat_compare_means(comparisons = my_comparisons,method = "wilcox",label = "p.signif")+
p3 <- p3+scale_color_lancet()+scale_fill_lancet()


#TIDE
tcga_tide_scores <- read.csv("/Users/gaibaowen/Downloads/CMS biomarker/CMS biomarker/tables/tcga_tide_scores.csv")
tide <- tcga_tide_scores
colnames(tide)[1] <- "ID"
tide <- merge(tide,lab_tcga2,by="ID")
tide <- tide[,c(1,4,17)]
colnames(tide) <- c("ID","expression","group")

group=levels(factor(tide$group))
comp=combn(group,2)
my_comparisons=list()
for(i in 1:ncol(comp)){my_comparisons[[i]]<-comp[,i]}

p4 <- ggplot(tide)+
  geom_half_violin(aes(as.numeric(factor(group,levels = my_sort))+0.1,expression,fill=factor(group,levels = my_sort)),side = 'r',cex=0.8)+
  geom_boxplot(aes(as.numeric(factor(group,levels = my_sort))+0.1,expression,fill=factor(group,levels = my_sort)),width=0.1,cex=0.8)+
  geom_jitter(aes(as.numeric(factor(group,levels = my_sort))-0.1,expression,color=factor(group,levels = my_sort)),width = 0.1,size=0.5)+
  scale_x_continuous(breaks = unique(as.numeric(factor(tide$group,levels = my_sort))), 
labels = unique(factor(tide$group,levels = my_sort)))+
  labs(title = "TIDE",x=NULL)+
  theme(plot.title = element_text(hjust = 0.5))
#+stat_compare_means(comparisons = my_comparisons,method = "wilcox",label = "p.signif")+
p4 <- p4+scale_color_lancet()+scale_fill_lancet()


pdf(file = "/Users/gaibaowen/Downloads/CMS biomarker/CMS_biomarker_new/result/immunoCheckpoint.pdf")
print(p1)
print(p2)
print(p3)
print(p4)
dev.off()

#immune_checkpoint
gene <- c("PDCD1", "CD274", "PDCD1LG2", "CD276", "CTLA4", "HAVCR2", "LAG3" ,"TIGIT", "BTLA")
tcga <- crc_combat[[1]]
labs <- lab.df[lab.df$Cohort=="TCGA",]
data <- as.data.frame(tcga[,gene]) 

data$id <- rownames(data)
labs$id <- rownames(labs)
dat <- merge(data,labs,by="id")
dat <- dat[,-c(11,13)]

dat_new <- pivot_longer(dat,c(2:10),names_to = "sample",values_to = "expression")

p <- ggplot(dat_new,aes(x=sample,y=expression,fill=RiskGroup))+
        geom_boxplot()+
        labs(title = "")+
        theme(plot.title = element_text(hjust = 0.5))+
        xlab("")+
        ylab("Expression")+
        stat_compare_means(aes(group=RiskGroup),method="wilcox.test",symnum.args=list(cutpoints = c(0, 0.001, 0.01, 0.05, 1), symbols = c("***", "**", "*", " ")),label = "p.signif")+
        theme_classic()+
        scale_fill_lancet() #+annotate(geom="text",x=1.5,y=1.5,label="*")

pdf(file = "/Users/gaibaowen/Downloads/CMS biomarker/CMS_biomarker_new/result/immunoGene.pdf")
print(p)
dev.off()
```

```{r}
#UMAP_siggene

normalise <- function(x, na.rm = TRUE) {
  ranx <- range(x, na.rm = na.rm)
  (x - ranx[1]) / diff(ranx)
}


tcga <- crc_combat[[1]]
data  <- tcga[,sig.genes]
clin <- clin[-which(is.na(clin$deepcc)),]
rownames(data) <- substr(rownames(data),1,12)
data <- data[rownames(data) %in% clin$id,]
clin <- clin[rownames(clin)%in% rownames(data), ]

df_data <- data

pc <- uwot::umap(df_data)
df_plot <- data.frame(UMAP1=normalise(pc[,1]), UMAP2=normalise(pc[,2]), CMS=clin$deepcc)

df_plot$CMS <- as.character(df_plot$CMS)

  p <- ggplot() +
    geom_point(data=df_plot,aes(colour=CMS, x=UMAP1, y=UMAP2),size=3, alpha=0.8, stroke = 0  ) +
     stat_ellipse(data=df_plot,aes(colour=CMS, x=UMAP1, y=UMAP2),level = 0.7,show.legend = F,alpha=0.6,size=1) +
    scale_color_manual(values=c("#E69E00","#0070B0","#CA78A6", "#009C73"), labels = c("CMS1", "CMS2", "CMS3", "CMS4"), guide="none") +
   #stat_density2d(data=df_plot,aes(fill=CMS,x=UMAP1,y=UMAP2,alpha=..density..),geom = "tile",contour = F,h=c(0.3,0.3))+
    stat_density2d(data=df_plot,geom="tile",aes(fill=CMS,x=UMAP1,y=UMAP2,alpha=..density..), contour=F, h=c(0.3, 0.3))+
    scale_alpha_continuous(range = c(0, 0.8), guide="none") +
    scale_fill_manual(values=c("#E69E00","#0070B0","#CA78A6", "#009C73"), labels = c("CMS1", "CMS2", "CMS3", "CMS4")) +
    scale_x_continuous(expand=c(0,0), limits = c(-0.2, 1.2)) + scale_y_continuous(expand=c(0,0), limits = c(-0.2, 1.2)) +
    
  
    theme(legend.title = element_blank(),
          legend.position = "none",
          axis.text.x=element_blank(),
          axis.text.y=element_blank(),
          text = element_text(family="Arial"),
          strip.background = element_rect(fill = "white",  linetype = "blank"))
   pdf("/Users/gaibaowen/Downloads/CMS biomarker/CMS_biomarker_new/result/siggene_umap.pdf",width = 5,height = 5)
   print(p)
   dev.off()
   
   
   #UMAP_df
   
   

data  <- df
clin <- clin[-which(is.na(clin$deepcc)),]
rownames(data) <- substr(rownames(data),1,12)
data <- data[rownames(data) %in% clin$id,]
clin <- clin[rownames(clin)%in% rownames(data), ]

df_data <- data

pc <- uwot::umap(df_data)
df_plot <- data.frame(UMAP1=normalise(pc[,1]), UMAP2=normalise(pc[,2]), CMS=clin$deepcc)

df_plot$CMS <- as.character(df_plot$CMS)

  p <- ggplot() +
    geom_point(data=df_plot,aes(colour=CMS, x=UMAP1, y=UMAP2),size=3, alpha=0.8, stroke = 0  ) +
     stat_ellipse(data=df_plot,aes(colour=CMS, x=UMAP1, y=UMAP2),level = 0.7,show.legend = F,alpha=0.6,size=1) +
    scale_color_manual(values=c("#E69E00","#0070B0","#CA78A6", "#009C73"), labels = c("CMS1", "CMS2", "CMS3", "CMS4"), guide="none") +
   #stat_density2d(data=df_plot,aes(fill=CMS,x=UMAP1,y=UMAP2,alpha=..density..),geom = "tile",contour = F,h=c(0.3,0.3))+
    stat_density2d(data=df_plot,geom="tile",aes(fill=CMS,x=UMAP1,y=UMAP2,alpha=..density..), contour=F, h=c(0.3, 0.3))+
    scale_alpha_continuous(range = c(0, 0.8), guide="none") +
    scale_fill_manual(values=c("#E69E00","#0070B0","#CA78A6", "#009C73"), labels = c("CMS1", "CMS2", "CMS3", "CMS4")) +
    scale_x_continuous(expand=c(0,0), limits = c(-0.2, 1.2)) + scale_y_continuous(expand=c(0,0), limits = c(-0.2, 1.2)) +
    
  
    theme(legend.title = element_blank(),
          legend.position = "none",
          axis.text.x=element_blank(),
          axis.text.y=element_blank(),
          text = element_text(family="Arial"),
          strip.background = element_rect(fill = "white",  linetype = "blank"))
   pdf("/Users/gaibaowen/Downloads/CMS biomarker/CMS_biomarker_new/result/df_umap.pdf",width = 5,height = 5)
   print(p)
   dev.off()
```



```{r}
#CMS_df_heatmap

 rownames(df) <- substr(rownames(df),1,12)
  clin<- clin[-which(is.na(clin$deepcc)),]
  clin <- clin[-which(duplicated(clin$id)),]
  df <- as.data.frame(df)
  df$id <- substr(rownames(df),1,12)
  df <- df[df$id %in% clin$id,]
  
  colnames(df) <- c("df1","df2","df3","df4","df5","df6","df7","df8","df9","df10","id")
  
  
  data <- merge(df,clin,by="id")
  data <- data[,c(1:11,40)]
  data <- data[order(data$deepcc),]
  rownames(data) <- data$id
  annotation_row <- as.data.frame(data[,12])
  rownames(annotation_row) <- data$id
  colnames(annotation_row) <- "CMS"
  dat <- data[,c(2:11)]
  
  scale_func <- function(x){
    rescale(x,to=c(-1,1))
  }
  dat <- apply(dat, 2, scale_func)
  
  annotation_row$CMS <- factor(annotation_row$CMS,levels = c("CMS1","CMS2","CMS3","CMS4"),ordered = TRUE)
  

  
  colors <- list(CMS=c(CMS1="#E69600",CMS2="#0070B0",CMS3="#CA78A6",CMS4="#009C73"))
  
  p<- pheatmap(t(dat), cluster_row=T, cluster_cols=F, fontsize=9, fontsize_row=6,cellheight = 8,cellwidth = 0.3, cutree_cols=4,show_rownames = TRUE,show_colnames = FALSE,treeheight_row = 0,treeheight_col = 0,
           breaks = c(-1, seq(-0.5, 0.5, length.out = 98), 1),
           annotation_col=annotation_row, annotation_legend = T, annotation_colors=colors)

  pdf("/Users/gaibaowen/Downloads/CMS biomarker/CMS_biomarker_new/result/heatmap.pdf")
  print(p)
  dev.off()
```

```{r}
#Correlation_gene_df

tcga <- crc_combat[[1]][,sig.genes]
r <- rcorr(tcga,df, type = "pearson")
r <- abs(r$r)
r <- r[-c(24:34),-c(1:23)]
colnames(r) <- c("df1","df2","df3","df4","df5","df6","df7","df8","df9","df10")
r <- as.data.frame(r)
r$sample <- rownames(r)

df.cor <- pivot_longer(data.frame(r),c(1:10),names_to = "Type",values_to = "Expression")
df.cor$Type <- factor(df.cor$Type,levels = c("df10","df9","df8","df7","df6","df5","df4","df3","df2","df1"))
df.cor$sample <- factor(df.cor$sample,levels = c("FCGR3A","CLEC5A","SLC11A1","SLAMF8","GAS1","CYP1B1","BGN","CCDC80","AEBP1","KCNMA1","DAPK1","ALOX5","CACNA1C","FRZB","MCM10","DUSP4","PLAGL2","LY6G6D","GNG4","TRIM7","NRXN2","ZNF853","ZCCHC24"))

p <- ggplot(data = df.cor,aes(x=sample,y=Type))+
          geom_point(aes(fill=Expression,size=Expression),shape=21,stroke=0,colour ="white")+
          #theme_classic()+
          theme_bw()+
          theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(),panel.border = element_blank())+
          paletteer::scale_fill_paletteer_c("grDevices::RdYlBu",direction = -1)+
          scale_size_area(max_size = 12) +
          xlab("")+
          ylab("")+
   theme( axis.text.x = element_text( angle = 90,color = "black", size = 8),
        axis.text.y = element_text( color = "black", size = 8),
          axis.ticks.length = unit(1, "cm"))
        
pdf(file = "/Users/gaibaowen/Downloads/CMS biomarker/CMS_biomarker_new/result/correlation_gene_df.pdf",width = 12,height = 6)
print(p)
dev.off()
```


```{r}
#C-index


#ourmodel

datasets <- crc_combat
clin_all <- crc_clin_all
rownames(clin_all) <- clin_all$id
get_survival <- function (clin)
{
    survival::Surv(clin[, "dfs.delay"], clin[, "dfs.event"] == 1)
}
i = 1
dat <- datasets[[i]][, sig.genes]
clin <- clin_all[substr(rownames(dat), 1, 12), ]
sur <- get_survival(clin)
ind <- !is.na(sur)
dat <- data.frame(scale(dat[ind, ]))
sur <- sur[ind, ]
model <- coxph(sur ~ .,data=dat)

c_index <- NULL
  get_survival <- function (clin)
{
    survival::Surv(clin[, "dfs.delay"], clin[, "dfs.event"] == 1)
  }
  
for(i in 1:length(datasets)) {
  title <- names(datasets)[i]
    # dat <- scale(datasets[[i]][, signature])
    dat <- data.frame(scale(datasets[[i]][,sig.genes]))
    clin <- clin_all[substr(rownames(dat), 1, 12), ]
    sur <- get_survival(clin)
    ind <- !is.na(sur)
    dat <- dat[ind, ]
    sur <- sur[ind, ]
    
    
    rs <- predict(model, dat)
    #oncotype <- calc_oncotypedx_crc(dat)
    #rs_oncotype <- oncotype$oncotypeDX_score
    
    clin <- clin[ind,]
    c <- concordance.index(x=rs,surv.time = clin$dfs.delay,surv.event = clin$dfs.event,method = "noether")
    
    #cindex.comp(C_index,C_index1)
    
#    CstatisticCI <- function(x) {
#  se <- x["S.D."]/sqrt(x["n"])
#  Low95 <- x["C Index"] - 1.96*se 
#  Upper95 <- x["C Index"] + 1.96*se 
#  cbind(x["C Index"], Low95, Upper95) 
#}
   #c <- 1-(CstatisticCI(rcorr.cens(rs_oncotype,sur)))
    c_index[i] <- list(c)
    names(c_index)[i] <- paste0("c_index_our",i)
}
  
  
  #oncotypeDX
  c_index2 <- NULL
  get_survival <- function (clin)
{
    survival::Surv(clin[, "dfs.delay"], clin[, "dfs.event"] == 1)
}
for(i in 1:length(datasets)) {
  title <- names(datasets)[i]
    # dat <- scale(datasets[[i]][, signature])
    dat <- data.frame(scale(datasets[[i]]))
    clin <- clin_all[substr(rownames(dat), 1, 12), ]
    sur <- get_survival(clin)
    ind <- !is.na(sur)
    dat <- dat[ind, ]
    sur <- sur[ind, ]
    
    #rs <- predict(model, dat)
    oncotype <- calc_oncotypedx_crc(dat)
    rs_oncotype <- oncotype$oncotypeDX_score
    
    clin <- clin[ind,]
    c <- concordance.index(x=rs_oncotype,surv.time = clin$dfs.delay,surv.event = clin$dfs.event,method = "noether")
    
    #cindex.comp(C_index,C_index1)
    
#    CstatisticCI <- function(x) {
#  se <- x["S.D."]/sqrt(x["n"])
#  Low95 <- x["C Index"] - 1.96*se 
#  Upper95 <- x["C Index"] + 1.96*se 
#  cbind(x["C Index"], Low95, Upper95) 
#}
   #c <- 1-(CstatisticCI(rcorr.cens(rs_oncotype,sur)))
    c_index2[i] <- list(c)
    names(c_index2)[i] <- paste0("c_index_OncotypeDX_",i)
}
  
  
  
  #CMS
  library(CMSclassifier)
argo <- as.data.frame(crc_combat[[4]])
argo <- clean_dat(argo,keytype = "SYMBOL",column = "ENTREZID")
dat <- as.data.frame(t(argo))
cms <- CMSclassifier::classifyCMS(dat)
cms <- as.data.frame(cms$predictedCMS)
clin_all$cms[1930:2516] <- cms$RF

clin_all$cms[which(!clin_all$cms %in% c("CMS1","CMS2","CMS3","CMS4"))] <- NA

clin_all$cms <- factor(clin_all$cms,levels = c("CMS1","CMS2","CMS3","CMS4"),labels = c("CMS1","CMS2","CMS3","CMS4"))

get_survival <- function (clin)
{
    survival::Surv(clin[, "dfs.delay"], clin[, "dfs.event"] == 1)
}
i = 1
dat <- datasets[[i]]
clin <- clin_all[substr(rownames(dat), 1, 12), ]
ind <- !is.na(clin$cms)
dat <- dat[ind,]
clin <- clin[ind,]

sur <- get_survival(clin)
ind <- !is.na(sur)
dat <- data.frame(scale(dat[ind, ]))
sur <- sur[ind, ]
clin <- clin[ind,]
model <- coxph(sur ~ clin$cms,data=dat)


c_index3 <- NULL

for(i in 1:length(datasets)) {
  title <- names(datasets)[i]
    
    dat <- data.frame(scale(datasets[[i]]))
    clin <- clin_all[substr(rownames(dat), 1, 12), ]
    ind <- !is.na(clin$cms)
    dat <- dat[ind,]
    clin <- clin[ind,]
    
    sur <- get_survival(clin)
    ind <- !is.na(sur)
    dat <- dat[ind, ]
    clin <- clin[ind,]
    sur <- sur[ind, ]
  
    rs <- predict(model, dat)
    
    c <- concordance.index(x=rs,surv.time = clin$dfs.delay,surv.event = clin$dfs.event,method = "noether")
    
    #cindex.comp(C_index,C_index1)
    
#    CstatisticCI <- function(x) {
#  se <- x["S.D."]/sqrt(x["n"])
#  Low95 <- x["C Index"] - 1.96*se 
#  Upper95 <- x["C Index"] + 1.96*se 
#  cbind(x["C Index"], Low95, Upper95) 
#}
   #c <- 1-(CstatisticCI(rcorr.cens(rs_oncotype,sur)))
    c_index3[i] <- list(c)
    names(c_index3)[i] <- paste0("c_index_cms",i)
}


save(c_index,c_index2,c_index3,file = "/Users/gaibaowen/Downloads/CMS biomarker/CMS_biomarker_new/result/C_index.rdata")
```

```{r}
rs_forest <- read.csv("/Users/gaibaowen/Downloads/CMS biomarker/CMS_biomarker_new/result/c_index.csv",header = FALSE)


p <- forestplot(labeltext=as.matrix(rs_forest[,c(1:3)]),
           mean=rs_forest$V4,
           lower=rs_forest$V5,
           upper=rs_forest$V6,
           is.summary=c(T,T,F,F,F,T,F,F,F,T,F,F,F,T,F,F,F),
           zero=0.5,
           boxsize=0.5,
           lineheight=unit(6,'mm'),
           graphwidth=unit(35,'mm'),
           colgap=unit(2,'mm'),
           lwd.zero=2,
           lwd.ci=2,
           col=fpColors(box="#ef233c",summary="#9e2a2b",lines='blue1',zero = 'grey'),
           xlab="C-index",
           lwd.xasix=2,
           lty.ci="solid",ci.vertices.height=0.15,clip=c(0,0.725),xticks.digits=6, graph.pos=4
)

pdf(file = "/Users/gaibaowen/Downloads/CMS biomarker/CMS_biomarker_new/result/C_index.pdf",width = 10,height = 8)
print(p)
dev.off()



c_index_violin <- read.csv("/Users/gaibaowen/Downloads/CMS biomarker/CMS_biomarker_new/result/c_index_violin.csv",header = T)
x=colnames(c_index_violin)[2]
y=colnames(c_index_violin)[3]
p <- ggviolin(c_index_violin, x="Group", y="C.index", fill = "Group", 
         xlab=x, ylab=y,
         legend.title=x,
         add = "boxplot", add.params = list(fill="white"))+coord_flip()+scale_fill_lancet()

pdf(file = "/Users/gaibaowen/Downloads/CMS biomarker/CMS_biomarker_new/result/C_index_2.pdf",width = 10,height = 8)
print(p)
dev.off()
```

```{r}
#超几何检验

clin <- clin_all[which(!is.na(clin_all$cms)),]
clin <- clin[clin$cohort=="TCGA",]
rownames(lab.df)[1:619] <- substr(rownames(lab.df)[1:619],1,12)
labs <- lab.df[rownames(lab.df) %in% rownames(clin),]
labs$id <- rownames(labs)
cms <- merge(labs,clin,by="id")
cms <- cms[,c(1,3,25)]
cms$cms <- factor(cms$cms,levels = c("CMS1","CMS2","CMS3","CMS4"),labels = c("CMS1","CMS2","CMS3","CMS4"))
cms_highrisk <- cms[cms$RiskGroup=="High Risk",]
cms_lowrisk <- cms[cms$RiskGroup=="Low Risk",]
summary(cms_highrisk)
summary(cms_lowrisk)
cms_plot <- data.frame(Group=c("High Risk","Low Risk"),
                       CMS1=c(36,32),
                       CMS2=c(128,78),
                       CMS3=c(33,31),
                       CMS4=c(101,15))
cms_plot<-  pivot_longer(cms_plot,cols=c(CMS1:CMS4),
                               names_to = 'CMS',
                               values_to = 'con')
cms_plot <- ddply(cms_plot,'Group',transform,percent_con=con/sum(con)*100)

p <-   ggplot(cms_plot, aes(Group, percent_con, fill = CMS)) +
    geom_bar(stat = 'identity',width = 0.5,colour='black')  +
    scale_y_continuous(expand = c(0,0))  +scale_fill_manual(values = c( "#E69600","#0070B0","#CA78A6","#009C73"))+
    theme(legend.title = element_blank(), legend.position = "none", axis.title.x = element_blank()) + labs(y="Percentage")

phyper(421,1227,786,525,lower.tail = F)

pdf(file = "/Users/gaibaowen/Downloads/CMS biomarker/CMS_biomarker_new/result/CMS_risk.pdf",width = 10,height = 8)
print(p)
dev.off()
```


```{r}
#药物治疗反应
load("/Users/gaibaowen/Downloads/CMS biomarker/CMS biomarker/data/GDSC_crc.RData")

data <- data.frame(scale(crc_cell_exp))
colnames(data)[which(colnames(data)=="LY6D")] <- "LY6G6D"
rs <- predict(model,data)
labs <- factor(rs > rs_cut, levels = c(F, T), labels = c("Low Risk", "High Risk"))
#labs <- factor(rs > mean(rs), levels = c(F, T), labels = c("Low Risk", "High Risk"))
lab.df <- data.frame(ID = as.numeric(rownames(crc_cell_exp)), group = labs,rs=rs)
crc_drug <- left_join(crc_drug, lab.df, by = c("Cosmic.sample.Id" = "ID"))



drug_list <- unique(crc_drug$Drug.name)

p_value <- foreach(i = 1:length(drug_list), .combine = "c") %do%{
drug <- drug_list[i]
drug_data <- crc_drug[crc_drug$Drug.name == drug, ]
wilcox.test(drug_data$IC50 ~ drug_data$group)$p.value
}

ind <- which(p_value < 0.05)
sig_drug <- drug_list[ind]



drug_list <- sig_drug
group_clr <- pal_nejm()(2)
p <- foreach(i = 1:length(drug_list)) %do%{
drug <- drug_list[i]
drug_data <- crc_drug[crc_drug$Drug.name == drug, ]
df_plot <- drug_data

variable <- c('Low Risk','High Risk')
my_sort <-factor(variable,levels = variable)

 ggplot(df_plot)+
  geom_half_violin(aes(as.numeric(factor(group,levels = my_sort))+0.1,IC50,fill=factor(group,levels = my_sort)),side = 'r',cex=0.8)+
  geom_boxplot(aes(as.numeric(factor(group,levels = my_sort))+0.1,IC50,fill=factor(group,levels = my_sort)),width=0.1,cex=0.8)+
  geom_jitter(aes(as.numeric(factor(group,levels = my_sort))-0.1,IC50,color=factor(group,levels = my_sort)),width = 0.1,size=1.5)+
  scale_x_continuous(breaks = unique(as.numeric(factor(df_plot$group,levels = my_sort))), 
labels = unique(factor(df_plot$group,levels = my_sort)))+
  labs(title=drug,x=NULL)+
  theme(plot.title = element_text(hjust = 0.5))
#+stat_compare_means(comparisons = my_comparisons,method = "wilcox",label = "p.signif")+


#ggviolin(df_plot, x = "group", y = "IC50", fill = "group",title = drug,
#          ylab = paste0(drug, ", IC50"),add = "boxplot",add.params = list(fill = "white"),
#         palette = rev(group_clr)) + 
#  stat_compare_means(label.y = max(df_plot$IC50)*1.5, label.x = 1.3, size = 4.5) +
  # stat_compare_means(comparisons = compare_list,label = "p.signif")+
#  theme(axis.title.x = element_blank(),
#        axis.title = element_text(family = "Arial", size = 12), 
#        axis.text = element_text(family = "Arial", size = 12), 
#        plot.title = element_text(hjust = 0.5),
#        legend.position = "none")
}
print(p)
pdf(file = "/Users/gaibaowen/Downloads/CMS biomarker/CMS_biomarker_new/result/drug_response.pdf")
print(p)
dev.off()




chemo_drug <- crc_drug_type_annot[crc_drug_type_annot$Type == "Chemotherapy drug",]$`Drug name`
drug_list <- intersect(sig_drug, chemo_drug)
# drug_list <- sig_drug
group_clr <- pal_nejm()(2)
p <- foreach(i = 1:length(drug_list)) %do%{
drug <- drug_list[i]
drug_data <- crc_drug[crc_drug$Drug.name == drug, ]
df_plot <- drug_data

variable <- c('Low Risk','High Risk')
my_sort <-factor(variable,levels = variable)

p <- ggplot(df_plot)+
  geom_half_violin(aes(as.numeric(factor(response,levels = my_sort))+0.1,rs,fill=factor(response,levels = my_sort)),side = 'r',cex=0.8)+
  geom_boxplot(aes(as.numeric(factor(response,levels = my_sort))+0.1,rs,fill=factor(response,levels = my_sort)),width=0.1,cex=0.8)+
  geom_jitter(aes(as.numeric(factor(response,levels = my_sort))-0.1,rs,color=factor(response,levels = my_sort)),width = 0.1,size=1.5)+
  scale_x_continuous(breaks = unique(as.numeric(factor(df_plot$response,levels = my_sort))), 
labels = unique(factor(df_plot$response,levels = my_sort)))+
  labs(title = "PRJEB23709",x=NULL)+
  theme(plot.title = element_text(hjust = 0.5))
#+stat_compare_means(comparisons = my_comparisons,method = "wilcox",label = "p.signif")+
p <- p+scale_color_lancet()+scale_fill_lancet()


#ggviolin(df_plot, x = "group", y = "IC50", fill = "group",title = drug,
#          ylab = paste0(drug, ", IC50"),add = "boxplot",add.params = list(fill = "white"),
#         palette = rev(group_clr)) + 
#  stat_compare_means(label.y = max(df_plot$IC50)*1.5, label.x = 1.3, size = 4.5) +
  # stat_compare_means(comparisons = compare_list,label = "p.signif")+
#  theme(axis.title.x = element_blank(),
#        axis.title = element_text(family = "Arial", size = 12), 
#        axis.text = element_text(family = "Arial", size = 12), 
#        plot.title = element_text(hjust = 0.5),
#        legend.position = "none")
}
print(p)
```


```{r}
#免疫治疗
load("/Users/gaibaowen/Downloads/免疫治疗数据集/Immunotherapy_datasets.rdata")
dat <- data.frame(scale(immune_dataset[[3]]))
rs <- predict(model,dat)

clin <- immune_dataset_clin[[3]]

get_survival <- function (clin)
{
    survival::Surv(clin[, "time"], clin[, "status"] == 1)
}
sur <- get_survival(clin)
rs_cut <- calc_cutoff_survivalroc(sur, rs, 60)

labs <- factor(rs > rs_cut, levels = c(F, T), labels = c("Low Risk", "High Risk"))
lab.df <- data.frame(id = rownames(dat), group = labs,rs=rs)



df_plot <- merge(lab.df,clin,by="id")
wilcox.test(df_plot$rs~df_plot$response)
rownames(df_plot) <- df_plot$id
df_plot <- df_plot[,c("group","response")]
df_plot <- data.frame(table(df_plot))
df_plot <- ddply(df_plot,'group',transform,percent_con=Freq/sum(Freq)*100)

a<- matrix(c(0,17,2,11),ncol=2,
                 dimnames = list(c('High Risk','Low Risk'),
                               c('R','NR')))

p <-   ggplot(df_plot, aes(group, percent_con, fill = response)) +
    geom_bar(stat = 'identity',width = 0.5,colour='black')  +
    scale_y_continuous(expand = c(0,0)) +
    theme(legend.title = element_blank(), legend.position = "top", axis.title.x = element_blank()) +
  geom_text(aes(label=paste0(round(percent_con,2),"%"),size=5))+
  labs(y="Percentage")+scale_fill_jco()

variable <- c('R','N')
my_sort <-factor(variable,levels = variable)

p <- ggplot(df_plot)+
  geom_half_violin(aes(as.numeric(factor(response,levels = my_sort))+0.1,rs,fill=factor(response,levels = my_sort)),side = 'r',cex=0.8)+
  geom_boxplot(aes(as.numeric(factor(response,levels = my_sort))+0.1,rs,fill=factor(response,levels = my_sort)),width=0.1,cex=0.8)+
  geom_jitter(aes(as.numeric(factor(response,levels = my_sort))-0.1,rs,color=factor(response,levels = my_sort)),width = 0.1,size=1.5)+
  scale_x_continuous(breaks = unique(as.numeric(factor(df_plot$response,levels = my_sort))), 
labels = unique(factor(df_plot$response,levels = my_sort)))+
  labs(title = "PRJEB23709",x=NULL)+
  theme(plot.title = element_text(hjust = 0.5))
#+stat_compare_means(comparisons = my_comparisons,method = "wilcox",label = "p.signif")+
p <- p+scale_color_lancet()+scale_fill_lancet()

 p <- plot_KMCurve(sur, labs, ylab="DFS", color = c("#377EB8", "#E41A1C"), legend.pos = "none", title = "PRJNA482620", xlab="Months", limit = 60)

pdf(file = "/Users/gaibaowen/Downloads/CMS biomarker/CMS_biomarker_new/result/immunotherapy_GSE126044.pdf")
print(p)
dev.off()
```
 
 
```{r}
#Table_one

clin <- read.csv("/Users/gaibaowen/Downloads/CMS biomarker/CMS_biomarker_new/result/clin_tableone.csv")
clin_new <- clin[,c("cohort","id","age","sex","tnm.stage","TNM.T","TNM.N","TNM.M","mmr","cms","location")]

clin_info <- clin_new %>% 
  dplyr::mutate(
                   Age = factor(ifelse(age <65,"<65 years old","≥65 years old"),levels = c("<65 years old","≥65 years old")),
                   Sex = factor(ifelse(sex == "F", "Female", ifelse(sex == "M", "Male", NA)), levels = c("Male", "Female")),
                   `TNM Stage` = factor(ifelse(`tnm.stage` %in% c(1, 2, 3, 4), `tnm.stage`, NA), levels = c(1, 2, 3, 4), labels = c("I", "II", "III", "IV")),
                   `T Stage` = factor(ifelse(`TNM.T` %in% c(1, 2, 3, 4), `TNM.T`, NA), levels = c(1,2,3,4), labels = c("T1", "T2", "T3", "T4")),
                   `N Stage` = factor(ifelse(`TNM.N` %in% c(0, 1, 2), `TNM.N`, NA), levels = c(0,1,2), labels = c("N0", "N1", "N2")),
                   `M Stage` = factor(ifelse(`TNM.M` %in% c(0, 1), `TNM.M`, NA), levels = c(0,1), labels = c("M0", "M1")),
                   `MSS/MSI Status` = factor(ifelse(`mmr` == "mss", "MSS", ifelse(`mmr` == "msi", "MSI", NA)), levels = c("MSI", "MSS"), labels = c("MSI", "MSS")),
                   `CMS Stage`=factor(`cms`,levels = c("CMS1","CMS2","CMS3","CMS4")),
                   `Tumor Location` = factor(`location`, levels = c("R", "L"),labels = c("Right","Left"))
                   )

clin_info <- clin_info[,c(1,12:20)]


ct_clin_all_cms <- read_csv("~/Downloads/CMS biomarker/CMS biomarker/data/ct_clin_all_cms.csv")
rownames(ct_clin_all_cms) <- ct_clin_all_cms$tuominID
ct_clin_all_cms <- ct_clin_all_cms[,-c(1,3)]
ct_clin_all_cms$location <- NA


clin_info_ct <- ct_clin_all_cms %>% 
  dplyr::mutate(
                   Age = factor(ifelse(age <65,"<65 years old","≥65 years old"),levels = c("<65 years old","≥65 years old")),
                   Sex = factor(ifelse(sex == "F", "Female", ifelse(sex == "M", "Male", NA)), levels = c("Male", "Female")),
                   `TNM Stage` = factor(ifelse(`tnm.stage` %in% c(1, 2, 3, 4), `tnm.stage`, NA), levels = c(1, 2, 3, 4), labels = c("I", "II", "III", "IV")),
                   `T Stage` = factor(ifelse(`tnm.t` %in% c(1, 2, 3, 4), `tnm.t`, NA), levels = c(1,2,3,4), labels = c("T1", "T2", "T3", "T4")),
                   `N Stage` = factor(ifelse(`tnm.n` %in% c(0, 1, 2), `tnm.n`, NA), levels = c(0,1,2), labels = c("N0", "N1", "N2")),
                   `M Stage` = factor(ifelse(`tnm.m` %in% c(0, 1), `tnm.m`, NA), levels = c(0,1), labels = c("M0", "M1")),
                   `MSS/MSI Status` = factor(ifelse(`mmr.status` == "mss", "MSS", ifelse(`mmr.status` == "msi", "MSI", NA)), levels = c("MSI", "MSS"), labels = c("MSI", "MSS")),
                   `CMS Stage`=factor(`cms`,levels = c("CMS1","CMS2","CMS3","CMS4")),
                   `Tumor Location` = factor(`location`, levels = c("R", "L"),labels = c("Right","Left"))
                   )

clin_info_ct <- clin_info_ct[,c(1,12:20)]

clin_info_all <- rbind(clin_info, clin_info_ct) %>% 
  dplyr::mutate(cohort = factor(cohort, levels = c("TCGA", "GSE39582","Meta-Validation","COCC","Training","Validation")))



table_one_fun <- function(clin_info_tab,                    #这里就是输入一个dataframe，其第一列是cohort信息，后面的诸列按照制表顺序排列各个需要统计的因素
                          clin_factor_var_colnames,         #这里需要输入一个character vector，告诉函数那些列名对应着分类变量
                          table_title,
                          table_width = 1000,               #table_width的单位是px
                          save_table = F,
                          save_table_position = "./",                         #指定输出html文件的输出位置(文件夹)
                          save_table_filename = "baseline_table.html"       #指定输出html文件的输出位置和文件名
                          ){
  
  #把NA值也纳入统计，进行队列中的各个变量的统计描述
  table1_1 <- tableone::CreateTableOne(vars = colnames(clin_info_tab)[-1], includeNA = T,
                                       data = clin_info_tab, 
                                       factorVars = clin_factor_var_colnames, 
                                       strata = colnames(clin_info_tab)[1])
  table1_1 <- as.data.frame(print(table1_1, 
                                  showAllLevels = TRUE, 
                                  printToggle = FALSE, 
                                  noSpaces = TRUE))
  table1_1 <- table1_1[-1, ] %>% 
    dplyr::filter(is.na(level) == F) %>% 
    select("level", levels(clin_info_tab[, 1])) 
  
  #排除NA值，进行队列中的各个变量的统计检验
  table1_2 <- tableone::CreateTableOne(vars = colnames(clin_info_tab)[-1], 
                                       data = clin_info_tab, 
                                       factorVars = clin_factor_var_colnames, 
                                       strata = colnames(clin_info_tab)[1])
  table1_2 <- as.data.frame(print(table1_2, 
                                  showAllLevels = TRUE, 
                                  printToggle = FALSE, 
                                  noSpaces = TRUE))
  table1_2 <- table1_2[-1, ] %>% 
    dplyr::filter(is.na(level) == F) %>% 
    select("p", "test")
  
  #两部分合起来
  rownames(table1_1) <- rownames(table1_2)
  table1 <- cbind(table1_1, table1_2)
  
  #调整每一个变量分组的名字的function
  subgroup_name_fun <- function(clin_info_tab, baseline_var_name_vec) {
    do.call(c, lapply(baseline_var_name_vec, function(i){
      if(is.factor(clin_info_tab[, i]) == F){
        a <- i
        } else if(is.factor(clin_info_tab[, i]) == T){
          a <- replicate(length(levels(clin_info_tab[, i])), i)
          }
      a
    }))
  }
  
  #画出基线表
  table1 <- table1 %>% 
    dplyr::mutate(row_name = rownames(table1)) %>% 
    dplyr::mutate(level = ifelse(level == "", str_c(str_extract(row_name, pattern = "^\\w+"), "(SD)", sep = " ") , str_c(level, "(%)", sep = " "))) %>% 
    dplyr::mutate(subgroup = subgroup_name_fun(clin_info_tab = clin_info_tab, 
                                               baseline_var_name_vec = colnames(clin_info_tab)[-1])) %>% 
    dplyr::select(-"test", -"row_name")
  
  
  table1 <- table1 %>%
    gt(rowname_col = "level",
       groupname_col = "subgroup") %>%
    tab_header(title = table_title) %>%
    tab_options(
        table.border.top.color = "white",
        table.border.bottom.color = "white",
        
        heading.border.bottom.color = "black",
        table_body.border.bottom.color = "black",
        
        table_body.vlines.color = "white", 
        table_body.hlines.color = "white",
        
        row_group.border.bottom.color = "white", 
        row_group.border.top.color = "white", 
        row_group.border.right.color = "white",
        row_group.border.left.color = "white",
        stub.border.color = "white",
        
        
        table_body.border.top.color = "black",
        table_body.border.top.style = "line",
        table.width = px(table_width)
        ) 
  
  if(save_table == T){
    table1 %>% gtsave(filename = save_table_filename, inline_css = F, path = save_table_position)
  }
  table1
}



table_one_fun(clin_info_tab = clin_info_all, 
              clin_factor_var_colnames = c("Sex" , "TNM Stage", "T Stage", "N Stage", "M Stage", "MSS/MSI Status", "CMS Stage","Tumor Location"), 
              table_title = "Table 1. Characteristics of patients in all cohorts",
              table_width = 650, 
              save_table = T, 
              save_table_position = "~/Desktop/", 
              save_table_filename = "baseline_table.html")
```



