---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
load("../data/crc_data_combat.RData")
load("../data/eps.rdata")
load("../data/argo_df.rdata")

# load_DeepCC_model <- function(prefix){
#      load(file = paste0(prefix, ".RData"))
#      classifer <- keras::load_model_hdf5(filepath =paste0(prefix, ".hdf5"))
#      list(classifier = classifer, levels = levels)
#    }
#    
#    CRC_TCGA <- load_DeepCC_model("../data/CRC_TCGA")
#    
#    argo_exp <- crc_combat[[4]]
#     eps <- clean_dat(argo_exp, keytype = "SYMBOL", column = "ENTREZID")
#     fs <- getFunctionalSpectra(eps)
#     
#     df <- get_DeepCC_features(CRC_TCGA, fs)
#     save(fs, df, file = "../rslt/argo_df.RData")
eps <- scale(as.matrix(eps))
# eps <- scale(log2(eps + abs(min(eps)) + 1))
    
calcEPCor <- function(ep, f){
  n <- ncol(ep)
  sapply(1:10, function(idx.feature){
    tmp <- unlist(mclapply(1:n, function(idx) cor(ep[,idx], f[, idx.feature]), mc.cores = 60))
    tmp[is.na(tmp)] <- 0
    names(tmp) <- colnames(ep)[1:n]
    tmp
  })
}

findBioMarker <- function(correlation, eps, cutoff, access, groups=NULL, n=10){
  library(org.Hs.eg.db)
  ep.average <- colMeans(eps)
  ep.genenames <- colnames(eps)
  ep.mad <- apply(eps, 2, mad)
  
  res <- do.call(rbind, lapply(1:10, function(idx){
    genes <- head(order(abs(correlation[,idx]), decreasing = T), n)
    df <- data.frame(Feature=idx,
                     Gene = ep.genenames[genes],
                     # Gene=select(org.Hs.eg.db, keytype = "ENTREZID", key=ep.genenames[genes], columns = "SYMBOL"),
                     AverageExperssion=ep.average[genes],
                     MAD=ep.mad[genes])
    
    # df <- df[df$Gene.ENTREZID %in% access, ]
    df <- df[df$Gene %in% access, ]
    # df <- df[df$AverageExperssion > cutoff, ]
    df <- df[order(df$MAD, decreasing = T), ]
    head(df, cutoff)
  }))
  if(!is.null(groups)) {
    res <- do.call(rbind, lapply(1:length(groups), function(i) {
      idx <- groups[[i]]
      tmp <- res[res$Feature %in% idx, ]
      tmp$Feature <- paste("FeatureGroup", i)
      # tmp[match(unique(tmp$Gene.ENTREZID), tmp$Gene.ENTREZID), ]
      tmp[match(unique(tmp$Gene), tmp$Gene), ]
    }))
  } 
  res
}
    
    eps <- eps
    df <- filter(data.frame(df),rownames(df) %in% rownames(eps))
    df <- as.matrix(df)
    
    ep.cor <- calcEPCor(eps, df)
    access <- colnames(eps)
    groups <- list(c(3,4,1,10), c(5,8),c(7,9,2,6))
    res <- findBioMarker(ep.cor, eps, 3, access, groups, n = 10)
    sig.radios <- unique(res$Gene)
```


```{r}
   get_survival <- function (clin)
    {
      survival::Surv(clin[, "dfs.delay"], clin[, "dfs.event"] == 1)
    }
    
    ct_clin <-read.csv("../data/ct_data_clin2.csv")
    radio_zs6y<- read.csv("../data/radiogenomic_zs6y_1218_data.csv")
    load("../data/clin_standard.rdata")
    load("../data/validation.rdata")
    
    dat <- eps[, sig.radios]
    clin <- clin_standard
    sur <- get_survival(clin)
    ind <- !is.na(sur)
    dat <- data.frame(scale(dat[ind, ]))
    sur <- sur[ind, ]
    model <- coxph(sur ~ .,data=dat)
    
    rs <- predict(model, dat)
    rs_cut <- calc_cutoff_survivalroc(sur, rs, 60)
    labs <- factor(rs > rs_cut, levels = c(F, T), labels = c("Low Risk", "High Risk"))
    
    p <- plot_KMCurve(sur, labs, ylab="DFS", color = c("#377EB8", "#E41A1C"), legend.pos = "none", title = NULL, xlab="Months", limit = 60)
    
    pdf(file="survival_analysis_ARGO.pdf",width = 10,height = 8)
    print(p)
    dev.off()
    
    dat <- data.frame(scale(validation[,sig.radios]))
    clin <- filter(ct_clin,ct_clin$tuominID %in% rownames(dat))
    dat <- filter(dat,rownames(dat) %in% clin$tuominID)
    sur <- get_survival(clin)
    ind <- !is.na(sur) 
    dat <- dat[ind, ]
    sur <- sur[ind, ]
    
    rs <- predict(model, dat)
    rs_cut <- calc_cutoff_survivalroc(sur, rs, 60)
    labs <- factor(rs > rs_cut, levels = c(F, T), labels = c("Low Risk", "High Risk"))
    
    p <- plot_KMCurve(sur, labs, ylab="DFS", color = c("#377EB8", "#E41A1C"), legend.pos = "none", title = NULL, xlab="Months", limit = 60)
    
    pdf(file="survival_analysis_Validation.pdf",width = 10,height = 8)
    print(p)
    dev.off()
```

